---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/somalik/kube-config.git
    targetRevision: HEAD
    path: kube-config
  destination:
    server: https://kubernetes.default.svc
#    namespace: myapp
  syncPolicy:    # create namespace if not present
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true    # check every 3 mins
      prune: true
